arm:
   arm_joint_controller:
    type: "position_controllers/JointTrajectoryController"
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    gains:
      joint1:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint2:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint3:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint4:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint5:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}
      joint6:   {p: 100.0, i: 0.0, d: 0.1, i_clamp: 0.0}




  
